version: '3.4'

services:
  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "7000:80"

  authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "6001:80"
      
  input:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "6002:80"
