version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: SCA.Gateway/Dockerfile

  authentication:
    image: authentication
    build:
      context: .
      dockerfile: SCA.Service.Auth/Dockerfile
      
  input:
    image: input
    build:
      context: .
      dockerfile: SCA.Service.Inputs/Dockerfile