version: '3.4'

services:

  db:
    container_name: mysql-db-01
    image: mysql:5.7
    ports:
      - 3306:3306
      - 33060:33060
    env_file:
      - mysql.env
    volumes:
      # Volume dos dados 
      - ./dados:/var/lib/mysql
      
  admin_db:
    container_name: mysql-admin-01
    image: nazarpc/phpmyadmin
    links:
      - db:mysql
    ports:
      - 8082:80
    depends_on:
      - db

  authentication:
    image: authentication
    build:
      context: .
      dockerfile: SCA.Service.Auth/Dockerfile
    ports:
      - "6001:80"
    env_file:
      - services.env
    depends_on:
      - admin_db      
      
  inputs:
    image: inputs
    build:
      context: .
      dockerfile: SCA.Service.Inputs/Dockerfile
    ports:
      - "6002:80"
    env_file:
      - services.env
    depends_on:
      - admin_db
      
  maintenance:
    image: maintenance
    build:
      context: .
      dockerfile: SCA.Service.Maintenance/Dockerfile
    ports:
      - "6003:80"
    env_file:
      - services.env
    depends_on:
      - admin_db
      
  monitoring:
    image: monitoring
    build:
      context: .
      dockerfile: SCA.Service.Monitoring/Dockerfile
    ports:
      - "6004:80"
    env_file:
      - services.env
    depends_on:
      - admin_db
      
  alert:
    image: alert
    build:
      context: .
      dockerfile: SCA.Service.Alert/Dockerfile
    ports:
      - "6005:80"
    env_file:
      - services.env
    depends_on:
      - admin_db
      
  web:
    image: web
    build:
      context: .
      dockerfile: SCA.Web/Dockerfile
    ports:
      - "81:80"
    env_file:
      - services.env
    depends_on:
      - alert
      
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: SCA.Gateway/Dockerfile
    ports:
      - "7000:80"
    env_file:
      - services.env
    depends_on:
      - authentication
      - inputs
      - maintenance
      - monitoring
      - alert
      - web
      
